# Generated by Django 6.0.3 on 2026-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'พนักงานประจำ'), ('contract', 'พนักงานสัญญาจ้าง'), ('daily', 'พนักงานรายวัน')], default='full_time', max_length=50, verbose_name='ประเภทการจ้างงาน'),
        ),
    ]
