# Generated by Django 6.0.3 on 2026-03-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'พนักงานประจำ'), ('contract', 'พนักงานสัญญาจ้าง'), ('part_time', 'พนักงานชั่วคราว')], default='full_time', max_length=50, verbose_name='ประเภทการจ้างงาน'),
        ),
    ]
