# Generated by Django 6.0.3 on 2026-03-14 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('hours_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attendance_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('social_security', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'period_month', 'period_year')},
            },
        ),
    ]
