# Generated by Django 6.0.3 on 2026-03-15 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payslip',
            name='cycle',
            field=models.CharField(choices=[('1H', 'งวดที่ 1 (ต้นเดือน)'), ('2H', 'งวดที่ 2 (สิ้นเดือน)')], default='2H', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'period_month', 'period_year', 'cycle')},
        ),
    ]
